<?php
require_once('MLADoc.php');
//1 pt = 1/72 in
$pdf = new MLADoc('Aggarwal', 'Yash', 'TAG English III', 'On my Love for Siddharth Kumar', 'Mr. Awesome');
$pdf->newParagraph("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue tempus justo, sit amet pellentesque nisl sagittis in. Aliquam sagittis feugiat nisl nec dapibus. Morbi ornare aliquam faucibus. Curabitur sit amet condimentum diam. Proin facilisis nisi a nulla ultricies ac interdum massa mattis. Nulla lacinia, dui id rutrum vehicula, velit lorem tempor arcu, vitae porta lectus nisi nec magna. Sed laoreet dui sapien.");
$pdf->newParagraph("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue tempus justo, sit amet pellentesque nisl sagittis in. Aliquam sagittis feugiat nisl nec dapibus. Morbi ornare aliquam faucibus. Curabitur sit amet condimentum diam. Proin facilisis nisi a nulla ultricies ac interdum massa mattis. Nulla lacinia, dui id rutrum vehicula, velit lorem tempor arcu, vitae porta lectus nisi nec magna. Sed laoreet dui sapien.");
$pdf->newParagraph("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue tempus justo, sit amet pellentesque nisl sagittis in. Aliquam sagittis feugiat nisl nec dapibus. Morbi ornare aliquam faucibus. Curabitur sit amet condimentum diam. Proin facilisis nisi a nulla ultricies ac interdum massa mattis. Nulla lacinia, dui id rutrum vehicula, velit lorem tempor arcu, vitae porta lectus nisi nec magna. Sed laoreet dui sapien.");
$pdf->newParagraph("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue tempus justo, sit amet pellentesque nisl sagittis in. Aliquam sagittis feugiat nisl nec dapibus. Morbi ornare aliquam faucibus. Curabitur sit amet condimentum diam. Proin facilisis nisi a nulla ultricies ac interdum massa mattis. Nulla lacinia, dui id rutrum vehicula, velit lorem tempor arcu, vitae porta lectus nisi nec magna. Sed laoreet dui sapien.");
$pdf->newParagraph("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue tempus justo, sit amet pellentesque nisl sagittis in. Aliquam sagittis feugiat nisl nec dapibus. Morbi ornare aliquam faucibus. Curabitur sit amet condimentum diam. Proin facilisis nisi a nulla ultricies ac interdum massa mattis. Nulla lacinia, dui id rutrum vehicula, velit lorem tempor arcu, vitae porta lectus nisi nec magna. Sed laoreet dui sapien.");
$pdf->Output();
